# Generated by Django 4.1.4 on 2023-01-25 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reg_Form', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aero_Eng',
        ),
        migrations.DeleteModel(
            name='Architecture_Eng',
        ),
        migrations.DeleteModel(
            name='Bio_Eng',
        ),
        migrations.DeleteModel(
            name='Civil_Eng',
        ),
        migrations.DeleteModel(
            name='Cse_Eng',
        ),
        migrations.DeleteModel(
            name='Culture',
        ),
        migrations.DeleteModel(
            name='Design',
        ),
        migrations.DeleteModel(
            name='Ece_Eng',
        ),
        migrations.DeleteModel(
            name='FoodAndTechnology',
        ),
        migrations.DeleteModel(
            name='ISBJ',
        ),
        migrations.DeleteModel(
            name='Management',
        ),
        migrations.DeleteModel(
            name='Mech_Eng',
        ),
        migrations.DeleteModel(
            name='School_of_Education_and_Research',
        ),
        migrations.DeleteModel(
            name='SFT',
        ),
        migrations.DeleteModel(
            name='SOFA',
        ),
        migrations.DeleteModel(
            name='Vedic_Science',
        ),
    ]
