# Generated by Django 4.1.5 on 2023-01-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reg_Form', '0002_delete_aero_eng_delete_architecture_eng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='College',
            field=models.CharField(max_length=20, verbose_name='College'),
        ),
        migrations.AlterField(
            model_name='users',
            name='Fullname',
            field=models.CharField(max_length=20, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='users',
            name='PhoneNo',
            field=models.CharField(max_length=10, verbose_name='Phone No.'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=20, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='users',
            name='event',
            field=models.CharField(max_length=50, verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
