# Generated by Django 4.1.4 on 2023-01-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reg_Form', '0003_admin_data_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_data',
            name='timestamp',
            field=models.CharField(max_length=40),
        ),
    ]
