# Generated by Django 4.1.5 on 2023-01-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reg_Form', '0003_alter_users_college_alter_users_fullname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='costs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=20, verbose_name='Event')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cost')),
            ],
        ),
    ]
