# Generated by Django 4.1.5 on 2023-01-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reg_Form', '0004_costs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costs',
            name='cost',
        ),
        migrations.AddField(
            model_name='costs',
            name='costs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costs'),
        ),
    ]
