# Generated by Django 4.1.5 on 2023-01-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reg_Form', '0005_remove_costs_cost_costs_costs'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
