# Generated by Django 4.1.5 on 2023-01-26 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reg_Form', '0006_users_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='costs',
        ),
        migrations.RemoveField(
            model_name='users',
            name='timestamp',
        ),
    ]
